services:
  postgres:
    image: postgres:14
    container_name: postgres_db_chongdia
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: chongdia_db
    ports:
      - "2002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_chongdia
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
