spring:
  application:
    name: chongdia
  bakongAccountId: phanet_chheun@wing
  exchangeRate: ...
  datasource:
    url: jdbc:postgresql://localhost:2002/chongdia_db
    username: admin 
    password: admin123 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
bakong:
  expirationTime: 2
  api:
    base-url: https://api-bakong.nbc.gov.kh
    token: ...
